language: python
python:
 - 2.6
 - 2.7

env:
 - DJANGO_VERSION=1.2.7
 - DJANGO_VERSION=1.3.7
 - DJANGO_VERSION=1.4.5
 - DJANGO_VERSION=1.5.1

install:
  - pip install -q mock==0.8 django-grappelli==2.3.8 Django==$DJANGO_VERSION
  - pip install . --use-mirrors

script: python setup.py test


notifications:
  irc: "irc.freenode.net#django-guardian"

